//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanJiKaiSheKeChengJiHuaBiao
    {
        public int ID { get; set; }
        public Nullable<int> BanJiID { get; set; }
        public string BanJiMing { get; set; }
        public Nullable<int> KeChengMing { get; set; }
        public Nullable<int> CaiYongJiaoXueJiHua { get; set; }
        public Nullable<int> KaiSheJiaoXueJieDuan { get; set; }
        public Nullable<int> ZhangJieBianHao { get; set; }
        public string ZhangJieMingChen { get; set; }
        public string JianYiKeShi { get; set; }
        public string ShouKeDeMoShi { get; set; }
        public Nullable<int> AnPaiJiaoYuan { get; set; }
        public Nullable<System.DateTime> AnPaiShiJian { get; set; }
        public string AnPaiZiYuan { get; set; }
        public string ShiJiKeShi { get; set; }
        public Nullable<int> ShiJiJiaoYuan { get; set; }
        public Nullable<System.DateTime> ShiJiShangKeShiJian { get; set; }
        public string ShiJiZiYuan { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<int> KeChengShunXuHao { get; set; }
        public Nullable<bool> ShiFouYiWanCheng { get; set; }
        public Nullable<bool> ShiFouYiQuXiao { get; set; }
        public Nullable<bool> ShiFouHeBing { get; set; }
    }
}
