//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuMenBiao
    {
        public int ID { get; set; }
        public string BuMenMingCheng { get; set; }
        public Nullable<int> DuiYingFuJiID { get; set; }
        public Nullable<int> Phone { get; set; }
        public string BuMenFuZheRen { get; set; }
        public string BuMenDengJiGuanXi { get; set; }
        public Nullable<System.DateTime> ChengLiTime { get; set; }
        public Nullable<bool> ShiFouQiYong { get; set; }
    }
}
