//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaoXueKeCheng
    {
        public int ID { get; set; }
        public string KeChengMing { get; set; }
        public Nullable<int> SuoShuJiaoXueJiHua { get; set; }
        public Nullable<int> SuoShuJiaoXueJieDuan { get; set; }
        public Nullable<int> JiaoXueJiHuaDeKaiZhanShunXuHao { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<System.DateTime> ZengJiaShiJian { get; set; }
        public string ZengJiaLaiYuan { get; set; }
        public Nullable<bool> ShiFouShanChu { get; set; }
    }
}
