//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaoYuanDuiYingJiHuaZhangJie
    {
        public int ID { get; set; }
        public Nullable<int> DuiYingJiHuaMing { get; set; }
        public string BanJiID { get; set; }
        public string BanJiMingChen { get; set; }
        public Nullable<int> LiLunKeCiShu { get; set; }
        public string RenKeLaoShi { get; set; }
        public string RenKeLaoShiMingChen { get; set; }
        public Nullable<int> ZhiShiDianXuHao { get; set; }
        public string ZhiShiDian { get; set; }
        public string CanJiaLaoShi { get; set; }
        public string CanJiaLaoShiID { get; set; }
        public Nullable<bool> ShiFouGeBan { get; set; }
        public Nullable<int> RenKeLaoShiKeShiShu { get; set; }
        public Nullable<int> CanJiaLaoShiKeShiShu { get; set; }
    }
}
