//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeChengShouKeZhangJie
    {
        public int ID { get; set; }
        public string SuoShuKeChengMing { get; set; }
        public Nullable<int> SuoShuKeChengBianHao { get; set; }
        public Nullable<int> ZhangJieBianHao { get; set; }
        public string ZhangJieMingChen { get; set; }
        public Nullable<int> JianYiKeShi { get; set; }
        public string JianYiShouKeZiYuan { get; set; }
        public Nullable<bool> ShiFouKeGeBanKaiZhan { get; set; }
        public Nullable<int> ZhangJieShunXuHao { get; set; }
        public string ZengJiaLaiYuan { get; set; }
        public Nullable<bool> ShiFouShanChu { get; set; }
    }
}
