//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeShiBiao
    {
        public int ID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string ClassID { get; set; }
        public string ClassName { get; set; }
        public string KeChengMingChen { get; set; }
        public string KeChengBianHao { get; set; }
        public Nullable<int> ShangKeCount { get; set; }
        public Nullable<bool> ShiFouWanChengBeKeCheng { get; set; }
        public string BeiZhu { get; set; }
        public string ZhuangTai { get; set; }
    }
}
