//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaikeLinshiBiao
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RQ { get; set; }
        public string SD { get; set; }
        public string JS { get; set; }
        public string BJ { get; set; }
        public string JY { get; set; }
        public string KC { get; set; }
    }
}
