//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZiYuanGuanLi
    {
        public int ID { get; set; }
        public string ZiYuanMing { get; set; }
        public string ZiYuanLeiXing { get; set; }
        public string ZiYuanWeiZhi { get; set; }
        public Nullable<int> ZiYuanRongNaRenShu { get; set; }
        public Nullable<int> BeiZhu { get; set; }
        public Nullable<bool> ShiFouYunHuDuoBanTongPai { get; set; }
    }
}
