//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenCiPaiKeShiDuanBiao
    {
        public int ID { get; set; }
        public string JiHuaMingChen { get; set; }
        public Nullable<int> JiHuaBianHao { get; set; }
        public Nullable<System.DateTime> ShiJian { get; set; }
        public string ShiDuan { get; set; }
        public string DuiYingShiJian { get; set; }
        public Nullable<bool> ShiFouPaiKe { get; set; }
        public string BeiZhu { get; set; }
    }
}
