//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaoXueJiHuaBiao
    {
        public int ID { get; set; }
        public string JiHuaBianHaoJiBanBen { get; set; }
        public Nullable<System.DateTime> KaiShiShiYongShiJian { get; set; }
        public Nullable<System.DateTime> ZhongZhiShiYongShiJian { get; set; }
        public string ShenHeRen { get; set; }
        public Nullable<bool> ShenHeShiFouTongGuo { get; set; }
        public Nullable<bool> ShiFouQiYong { get; set; }
    }
}
