//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaoYuanDaiKeBiao
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RiQi { get; set; }
        public string ClassName { get; set; }
        public string ShiJianDuan { get; set; }
        public string ShiJianMing { get; set; }
        public string KeChengBianHao { get; set; }
        public string KeChengMingChen { get; set; }
        public string ZhangJieBianHao { get; set; }
        public string ZhangJieMingChen { get; set; }
        public string ZiYuanBianHao { get; set; }
        public string ZiYuanMingChen { get; set; }
        public string JiaoYuanBianHao { get; set; }
        public string JiaoYuanMingChen { get; set; }
        public string ShiShiShiJian { get; set; }
        public string CanJiaRenYuan { get; set; }
        public string BeiZhu { get; set; }
        public string ZhuangTai { get; set; }
    }
}
