//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YuanGongBiao
    {
        public int ID { get; set; }
        public string RuGangShiJian { get; set; }
        public string JiaoYuanMingChen { get; set; }
        public Nullable<int> ZhiWeiID { get; set; }
        public string ShanChangKeCheng { get; set; }
        public string BeiZhu { get; set; }
        public Nullable<int> YuanGongZhuangTai { get; set; }
        public string MiMa { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
    }
}
